USE [DB_TestLogFile]
GO

/****** Object:  Table [Log].[DimUri]    Script Date: 31.07.2019 16:00:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Log].[DimUri](
	[UriId] [int] IDENTITY(1,1) NOT NULL,
	[UriName] [varchar](200) NOT NULL,
 CONSTRAINT [PK_Uri] PRIMARY KEY CLUSTERED 
(
	[UriId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

EXEC Log.usp_DimUri_Feed