USE [DB_TestLogFile]
GO

/****** Object:  Table [Log].[DimNumber]    Script Date: 31.07.2019 15:59:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Log].[DimNumber](
	[NumberId] [int] IDENTITY(1,1) NOT NULL,
	[Number] [nvarchar](50) NULL,
 CONSTRAINT [PK_numbers] PRIMARY KEY CLUSTERED 
(
	[NumberId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

EXEC Log.usp_DimNumber_Feed