USE [DB_TestLogFile]
GO

/****** Object:  Table [Log].[DimIp]    Script Date: 31.07.2019 15:58:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Log].[DimIp](
	[IpId] [int] IDENTITY(1,1) NOT NULL,
	[Ip] [varchar](200) NULL,
 CONSTRAINT [PK_IPs] PRIMARY KEY CLUSTERED 
(
	[IpId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

EXEC Log.usp_DimIp_Feed