USE [DB_TestLogFile]
GO

/****** Object:  Table [Log].[DimTrk]    Script Date: 31.07.2019 15:59:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Log].[DimTrk](
	[TrkId] [bigint] IDENTITY(1,1) NOT NULL,
	[TrkCode] [int] NULL,
	[TrkNum] [int] NULL,
	[TrkName] [varchar](200) NULL,
 CONSTRAINT [PK_trks] PRIMARY KEY CLUSTERED 
(
	[TrkId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

EXEC Log.usp_DimTrk_Feed