USE [DB_TestLogFile]
GO

/****** Object:  Table [Log].[DimTrunkCodec]    Script Date: 31.07.2019 16:00:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Log].[DimTrunkCodec](
	[TrunkCodecId] [bigint] IDENTITY(1,1) NOT NULL,
	[TrunkCodecName] [varchar](200) NULL,
 CONSTRAINT [PK_DimTrunkCodec] PRIMARY KEY CLUSTERED 
(
	[TrunkCodecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

EXEC Log.usp_DimTrunkCodec_Feed